; Elektron Monomachine-inspired SuperWave family
; Models the SWAVE SAW / PULSE / ENS machines as presets on one engine.
; Inputs: gate (ch 1), pitch_hz (ch 2), velocity (ch 3)

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))

(defmacro pulse_from_phase (phase width)
  (scale (lt phase width) 0 1 -1 1))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(param amp_attack_ms   @default 4    @min 1     @max 5000 @unit ms)
(param amp_decay_ms    @default 140  @min 1     @max 5000 @unit ms)
(param amp_sustain     @default 0.82 @min 0     @max 1)
(param amp_release_ms  @default 180  @min 1     @max 5000 @unit ms)

(param filt_attack_ms  @default 3    @min 1     @max 5000 @unit ms)
(param filt_decay_ms   @default 180  @min 1     @max 5000 @unit ms)
(param filt_sustain    @default 0.18 @min 0     @max 1)
(param filt_release_ms @default 220  @min 1     @max 5000 @unit ms)

(param cutoff          @default 4200 @min 80    @max 12000 @unit Hz)
(param resonance       @default 0.8  @min 0.35  @max 3.5)
(param filter_env_amt  @default 2600 @min -6000 @max 6000 @unit Hz)
(param keytrack        @default 0.35 @min 0     @max 2)

(param saw_mix         @default 1.0  @min 0     @max 1)
(param pulse_mix       @default 0.0  @min 0     @max 1)
(param pulse_width     @default 0.5  @min 0.04  @max 0.96)
(param detune_cents    @default 16   @min 0     @max 45 @unit cents)
(param motion_rate     @default 0.22 @min 0.01  @max 8 @unit Hz)
(param motion_depth    @default 0.08 @min 0     @max 0.4 @unit st)
(param phase_smear     @default 0.14 @min 0     @max 0.5)
(param sub_level       @default 0.0  @min 0     @max 1)
(param noise_level     @default 0.0  @min 0     @max 0.25)
(param drive           @default 1.15 @min 0.5   @max 4)
(param brightness      @default 0.28 @min 0     @max 1)
(param swarm           @default 0.0  @min 0     @max 1)
(param comb_amt        @default 0.0  @min 0     @max 1)
(param comb_time       @default 42   @min 1     @max 2205 @unit samples)
(param fm_smear        @default 0.0  @min 0     @max 1.5)
(param pwm_warp        @default 0.0  @min 0     @max 0.6)
(param chaos           @default 0.0  @min 0     @max 1)
(param gain            @default 0.11 @min 0     @max 1)

(def amp_env (adsr amp_attack_ms amp_decay_ms amp_sustain amp_release_ms))
(def filt_env (adsr filt_attack_ms filt_decay_ms filt_sustain filt_release_ms))

(def ln2 (log 2))
(def motion_lfo_a (sin (* twopi (phasor motion_rate))))
(def motion_lfo_b (sin (* twopi (phasor (* motion_rate 1.31)))))
(def motion_lfo_c (sin (* twopi (phasor (* motion_rate 0.73)))))
(def motion_ratio_a (exp (* ln2 (/ (* motion_lfo_a motion_depth) 12))))
(def motion_ratio_b (exp (* ln2 (/ (* motion_lfo_b motion_depth) 12))))
(def motion_ratio_c (exp (* ln2 (/ (* motion_lfo_c motion_depth) 12))))
(def chaos_trig (lt (phasor (+ 0.08 (* chaos 18))) 0.002))
(def chaos_step (latch (noise) chaos_trig))
(def fm_ratio_a (exp (* ln2 (/ (* motion_lfo_b fm_smear 7) 12))))
(def fm_ratio_b (exp (* ln2 (/ (* chaos_step fm_smear 12) 12))))
(def pwm_mod (clip (+ pulse_width (* motion_lfo_a pwm_warp 0.22) (* chaos_step pwm_warp 0.18)) 0.03 0.97))

(def detune_base (/ detune_cents 100))
(def r_m3 (semi_ratio (* detune_base -1.00)))
(def r_m2 (semi_ratio (* detune_base -0.66)))
(def r_m1 (semi_ratio (* detune_base -0.33)))
(def r_0 1.0)
(def r_p1 (semi_ratio (* detune_base 0.33)))
(def r_p2 (semi_ratio (* detune_base 0.66)))
(def r_p3 (semi_ratio (* detune_base 1.00)))

(def ph_m3 (wrap (+ (phasor (* pitch r_m3 motion_ratio_a fm_ratio_a)) (* phase_smear 0.00)) 0 1))
(def ph_m2 (wrap (+ (phasor (* pitch r_m2 motion_ratio_b fm_ratio_b)) (* phase_smear 0.07)) 0 1))
(def ph_m1 (wrap (+ (phasor (* pitch r_m1 motion_ratio_c fm_ratio_a)) (* phase_smear 0.13)) 0 1))
(def ph_0  (wrap (+ (phasor (* pitch r_0 fm_ratio_b)) (* phase_smear 0.19)) 0 1))
(def ph_p1 (wrap (+ (phasor (* pitch r_p1 motion_ratio_c fm_ratio_a)) (* phase_smear 0.29)) 0 1))
(def ph_p2 (wrap (+ (phasor (* pitch r_p2 motion_ratio_b fm_ratio_b)) (* phase_smear 0.37)) 0 1))
(def ph_p3 (wrap (+ (phasor (* pitch r_p3 motion_ratio_a fm_ratio_a)) (* phase_smear 0.43)) 0 1))

(def saw_stack
  (/ (+ (scale ph_m3 0 1 -1 1)
        (scale ph_m2 0 1 -1 1)
        (scale ph_m1 0 1 -1 1)
        (scale ph_0  0 1 -1 1)
        (scale ph_p1 0 1 -1 1)
        (scale ph_p2 0 1 -1 1)
        (scale ph_p3 0 1 -1 1))
     7))

(def pulse_stack
  (/ (+ (pulse_from_phase ph_m3 pwm_mod)
        (pulse_from_phase ph_m2 pwm_mod)
        (pulse_from_phase ph_m1 pwm_mod)
        (pulse_from_phase ph_0  pwm_mod)
        (pulse_from_phase ph_p1 pwm_mod)
        (pulse_from_phase ph_p2 pwm_mod)
        (pulse_from_phase ph_p3 pwm_mod))
     7))

(def sub (pulse_from_phase (phasor (/ pitch 2)) 0.5))
(def super_stack (mix saw_stack pulse_stack swarm))
(def stack (+ (* saw_stack saw_mix)
              (* pulse_stack pulse_mix)
              (* super_stack swarm 0.6)
              (* sub sub_level)
              (* chaos_step chaos 0.3)
              (* (noise) noise_level)))
(def combed (+ stack (* (delay stack comb_time) comb_amt)))
(def voiced (* combed (+ 0.3 (* 0.7 velocity))))
(def driven (tanh (* (+ voiced (* super_stack chaos 0.55)) drive)))
(def filter_cutoff
  (clip (+ cutoff (* filt_env filter_env_amt) (* pitch keytrack) (* brightness 1600)) 60 11000))
(def filtered (biquad driven filter_cutoff resonance 1 0))
(def edge (biquad driven (clip (* filter_cutoff 1.7) 120 12000) 0.6 1 1))
(out (* (+ filtered (* edge brightness 0.22)) amp_env velocity gain) 1 @name audio)
