; Elektron Monomachine-inspired DigiPRO family
; Approximates the DigiPRO WAVE / DENS / DDRW / BBOX machines as a single
; digital wavetable-style engine with presets.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(defmacro pulse_from_phase (phase width)
  (scale (lt phase width) 0 1 -1 1))

(defmacro crush (sig levels)
  (def safe_levels (max 4 levels))
  (def norm (* (+ sig 1) 0.5))
  (def stepped (/ (floor (* norm safe_levels)) safe_levels))
  (- (* stepped 2) 1))

(param amp_attack_ms   @default 3    @min 1     @max 5000 @unit ms)
(param amp_decay_ms    @default 180  @min 1     @max 5000 @unit ms)
(param amp_sustain     @default 0.7  @min 0     @max 1)
(param amp_release_ms  @default 150  @min 1     @max 5000 @unit ms)

(param morph           @default 1.1  @min 0     @max 4)
(param shape           @default 0.35 @min 0     @max 1)
(param formant         @default 1.8  @min 0.5   @max 6)
(param detune_cents    @default 8    @min 0     @max 40 @unit cents)
(param unison          @default 0.22 @min 0     @max 1)
(param sync_amt        @default 0.0  @min 0     @max 1)
(param alias           @default 0.28 @min 0     @max 1)
(param noise_level     @default 0.0  @min 0     @max 1)
(param table_jump      @default 0.0  @min 0     @max 1)
(param phase_distort   @default 0.0  @min 0     @max 1)
(param comb_amt        @default 0.0  @min 0     @max 1)
(param comb_time       @default 23   @min 1     @max 2205 @unit samples)
(param vowel_amt       @default 0.0  @min 0     @max 1)

(param cutoff          @default 5200 @min 60    @max 12000 @unit Hz)
(param resonance       @default 0.8  @min 0.35  @max 3.5)
(param filter_env_amt  @default 900  @min -4000 @max 4000 @unit Hz)
(param keytrack        @default 0.24 @min 0     @max 2)
(param drive           @default 1.2  @min 0.5   @max 4)
(param gain            @default 0.12 @min 0     @max 1)

(def amp_env (adsr amp_attack_ms amp_decay_ms amp_sustain amp_release_ms))
(def filt_env (adsr 2 90 0.0 140))

(def detune_semi (/ detune_cents 100))
(def phase_master (phasor pitch))
(def phase_slave (phasor (* pitch (semi_ratio detune_semi))))
(make-history slave_hist)
(def slave_prev (read-history slave_hist))
(def slave_wrap (lt phase_slave slave_prev))
(write-history slave_hist phase_slave)
(def slave_reset (* slave_wrap sync_amt))
(def phase_sync (phasor (* pitch (semi_ratio (* detune_semi -1))) slave_reset))
(def jump_trig (lt (phasor (+ 0.05 (* table_jump 32))) 0.002))
(def jump_noise (latch (noise) jump_trig))
(def jump_amt (* table_jump 0.85 jump_noise))
(def warped_phase (wrap (+ phase_master (* (sin (* twopi phase_master)) phase_distort 0.25) jump_amt) 0 1))

(def wave_a (sin (* twopi warped_phase)))
(def wave_b (tanh (* (+ 1 (* shape 5)) (scale warped_phase 0 1 -1 1))))
(def wave_c (+ (* (- 1 shape) (pulse_from_phase warped_phase 0.5))
               (* shape (pulse_from_phase warped_phase (clip (+ 0.16 (* shape 0.58) (* jump_amt 0.3)) 0.05 0.95)))))
(def formant_mod (+ 1 (* formant (+ 0.3 (* 0.7 shape)))))
(def wave_d (sin (+ (* twopi warped_phase) (* 2.2 (sin (* twopi warped_phase formant_mod))))))
(def wave_e (+ (* 0.6 (sin (* twopi warped_phase)))
               (* 0.24 (sin (* twopi warped_phase 2.01)))
               (* 0.16 (sin (* twopi warped_phase 3.97)))))

(def ab (mix wave_a wave_b (clip morph 0 1)))
(def cd (mix wave_c wave_d (clip (- morph 1) 0 1)))
(def de (mix wave_d wave_e (clip (- morph 2) 0 1)))
(def digital_wave_1 (mix ab cd (clip (- morph 1) 0 1)))
(def digital_wave_2 (mix cd de (clip (- morph 2) 0 1)))
(def digital_wave (mix digital_wave_1 digital_wave_2 (clip (- morph 3) 0 1)))
(def vowel_peak_a (biquad digital_wave (clip (+ 700 (* formant 380) (* vowel_amt 1200)) 100 9000) 1.8 1 2))
(def vowel_peak_b (biquad digital_wave (clip (+ 1800 (* shape 2100) (* vowel_amt 1600)) 200 11000) 1.4 1 2))

(def layer2 (+ (* 0.65 (sin (* twopi phase_sync)))
               (* 0.35 (tanh (* 2.4 (scale phase_sync 0 1 -1 1))))))
(def dens_layer (+ (* digital_wave (- 1 unison))
                   (* layer2 unison)
                   (* vowel_peak_a vowel_amt 0.4)
                   (* vowel_peak_b vowel_amt 0.28)
                   (* (noise) noise_level 0.35)))
(def crushed (mix dens_layer (crush dens_layer (+ 8 (* alias 248))) alias))
(def combed (+ crushed (* (delay crushed comb_time) comb_amt)))
(def driven (tanh (* combed drive)))
(def digi_cutoff (clip (+ cutoff (* pitch keytrack) (* filt_env filter_env_amt)) 80 11000))
(def filtered (biquad driven digi_cutoff resonance 1 0))
(out (* filtered amp_env velocity gain) 1 @name audio)
