; Elektron Monomachine-inspired SuperWave family
; Models the SWAVE SAW / PULSE / ENS machines as presets on one engine.
; Inputs: gate (ch 1), pitch_hz (ch 2), velocity (ch 3)

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(defmacro pulse_from_phase (phase width)
  (scale (lt phase width) 0 1 -1 1))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(param amp_attack_ms   @default 4    @min 1     @max 5000 @unit ms)
(param amp_decay_ms    @default 140  @min 1     @max 5000 @unit ms)
(param amp_sustain     @default 0.82 @min 0     @max 1)
(param amp_release_ms  @default 180  @min 1     @max 5000 @unit ms)

(param filt_attack_ms  @default 3    @min 1     @max 5000 @unit ms)
(param filt_decay_ms   @default 180  @min 1     @max 5000 @unit ms)
(param filt_sustain    @default 0.18 @min 0     @max 1)
(param filt_release_ms @default 220  @min 1     @max 5000 @unit ms)

(param cutoff          @default 4200 @min 80    @max 12000 @unit Hz @mod true @mod-mode additive)
(param resonance       @default 0.8  @min 0.35  @max 3.5 @mod true @mod-mode additive)
(param filter_env_amt  @default 2600 @min -6000 @max 6000 @unit Hz @mod true @mod-mode additive)
(param keytrack        @default 0.35 @min 0     @max 2)

(param saw_mix         @default 1.0  @min 0     @max 1 @mod true @mod-mode additive)
(param pulse_mix       @default 0.0  @min 0     @max 1 @mod true @mod-mode additive)
(param pulse_width     @default 0.5  @min 0.04  @max 0.96 @mod true @mod-mode additive)
(param detune_cents    @default 16   @min 0     @max 45 @unit cents @mod true @mod-mode additive)
(param motion_rate     @default 0.22 @min 0.01  @max 8 @unit Hz @mod true @mod-mode additive)
(param motion_depth    @default 0.08 @min 0     @max 0.4 @unit st @mod true @mod-mode additive)
(param phase_smear     @default 0.14 @min 0     @max 0.5 @mod true @mod-mode additive)
(param sub_level       @default 0.0  @min 0     @max 1 @mod true @mod-mode additive)
(param noise_level     @default 0.0  @min 0     @max 0.25 @mod true @mod-mode additive)
(param drive           @default 1.15 @min 0.5   @max 4 @mod true @mod-mode additive)
(param brightness      @default 0.28 @min 0     @max 1 @mod true @mod-mode additive)
(param swarm           @default 0.0  @min 0     @max 1 @mod true @mod-mode additive)
(param comb_amt        @default 0.0  @min 0     @max 1 @mod true @mod-mode additive)
(param comb_time       @default 42   @min 1     @max 2205 @unit samples @mod true @mod-mode additive)
(param fm_smear        @default 0.0  @min 0     @max 1.5 @mod true @mod-mode additive)
(param pwm_warp        @default 0.0  @min 0     @max 0.6 @mod true @mod-mode additive)
(param chaos           @default 0.0  @min 0     @max 1 @mod true @mod-mode additive)
(param gain            @default 0.11 @min 0     @max 1)

(def amp_env (adsr gate trigger amp_attack_ms amp_decay_ms amp_sustain amp_release_ms))
(def filt_env (adsr gate trigger filt_attack_ms filt_decay_ms filt_sustain filt_release_ms))

(def ln2 (log 2))
(def motion_lfo_a (sin (* twopi (phasor (mod motion_rate)))))
(def motion_lfo_b (sin (* twopi (phasor (* (mod motion_rate) 1.31)))))
(def motion_lfo_c (sin (* twopi (phasor (* (mod motion_rate) 0.73)))))
(def motion_ratio_a (exp (* ln2 (/ (* motion_lfo_a (mod motion_depth)) 12))))
(def motion_ratio_b (exp (* ln2 (/ (* motion_lfo_b (mod motion_depth)) 12))))
(def motion_ratio_c (exp (* ln2 (/ (* motion_lfo_c (mod motion_depth)) 12))))
(def chaos_trig (lt (phasor (+ 0.08 (* (mod chaos) 18))) 0.002))
(def chaos_step (latch (noise) chaos_trig))
(def fm_ratio_a (exp (* ln2 (/ (* motion_lfo_b (mod fm_smear) 7) 12))))
(def fm_ratio_b (exp (* ln2 (/ (* chaos_step (mod fm_smear) 12) 12))))
(def pwm_mod (clip (+ (mod pulse_width) (* motion_lfo_a (mod pwm_warp) 0.22) (* chaos_step (mod pwm_warp) 0.18)) 0.03 0.97))

(def detune_base (/ (mod detune_cents) 100))
(def r_m3 (semi_ratio (* detune_base -1.00)))
(def r_m2 (semi_ratio (* detune_base -0.66)))
(def r_m1 (semi_ratio (* detune_base -0.33)))
(def r_0 1.0)
(def r_p1 (semi_ratio (* detune_base 0.33)))
(def r_p2 (semi_ratio (* detune_base 0.66)))
(def r_p3 (semi_ratio (* detune_base 1.00)))

(def ph_m3 (wrap (+ (phasor (* pitch r_m3 motion_ratio_a fm_ratio_a)) (* (mod phase_smear) 0.00)) 0 1))
(def ph_m2 (wrap (+ (phasor (* pitch r_m2 motion_ratio_b fm_ratio_b)) (* (mod phase_smear) 0.07)) 0 1))
(def ph_m1 (wrap (+ (phasor (* pitch r_m1 motion_ratio_c fm_ratio_a)) (* (mod phase_smear) 0.13)) 0 1))
(def ph_0  (wrap (+ (phasor (* pitch r_0 fm_ratio_b)) (* (mod phase_smear) 0.19)) 0 1))
(def ph_p1 (wrap (+ (phasor (* pitch r_p1 motion_ratio_c fm_ratio_a)) (* (mod phase_smear) 0.29)) 0 1))
(def ph_p2 (wrap (+ (phasor (* pitch r_p2 motion_ratio_b fm_ratio_b)) (* (mod phase_smear) 0.37)) 0 1))
(def ph_p3 (wrap (+ (phasor (* pitch r_p3 motion_ratio_a fm_ratio_a)) (* (mod phase_smear) 0.43)) 0 1))

(def saw_stack
  (/ (+ (scale ph_m3 0 1 -1 1)
        (scale ph_m2 0 1 -1 1)
        (scale ph_m1 0 1 -1 1)
        (scale ph_0  0 1 -1 1)
        (scale ph_p1 0 1 -1 1)
        (scale ph_p2 0 1 -1 1)
        (scale ph_p3 0 1 -1 1))
     7))

(def pulse_stack
  (/ (+ (pulse_from_phase ph_m3 pwm_mod)
        (pulse_from_phase ph_m2 pwm_mod)
        (pulse_from_phase ph_m1 pwm_mod)
        (pulse_from_phase ph_0  pwm_mod)
        (pulse_from_phase ph_p1 pwm_mod)
        (pulse_from_phase ph_p2 pwm_mod)
        (pulse_from_phase ph_p3 pwm_mod))
     7))

(def sub (pulse_from_phase (phasor (/ pitch 2)) 0.5))
(def super_stack (mix saw_stack pulse_stack (clip (mod swarm) 0 1)))
(def stack (+ (* saw_stack (clip (mod saw_mix) 0 1))
              (* pulse_stack (clip (mod pulse_mix) 0 1))
              (* super_stack (clip (mod swarm) 0 1) 0.6)
              (* sub (clip (mod sub_level) 0 1))
              (* chaos_step (clip (mod chaos) 0 1) 0.3)
              (* (noise) (clip (mod noise_level) 0 0.25))))
(def combed (+ stack (* (delay stack (clip (mod comb_time) 1 2205)) (clip (mod comb_amt) 0 1))))
(def voiced (* combed (+ 0.3 (* 0.7 velocity))))
(def driven (tanh (* (+ voiced (* super_stack (clip (mod chaos) 0 1) 0.55)) (mod drive))))
(def filter_cutoff
  (clip (+ (mod cutoff) (* filt_env (mod filter_env_amt)) (* pitch keytrack) (* (mod brightness) 1600)) 60 11000))
(def filtered (biquad driven filter_cutoff (clip (mod resonance) 0.35 3.5) 1 0))
(def edge (biquad driven (clip (* filter_cutoff 1.7) 120 12000) 0.6 1 1))
(out (* (+ filtered (* edge (mod brightness) 0.22)) amp_env velocity gain) 1 @name audio)
