; Elektron Monomachine-inspired FM+ family
; Covers FM+ STATIC / PARALLEL / DYNAMIC as presets on one engine.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(param amp_attack_ms    @default 8    @min 1     @max 5000 @unit ms)
(param amp_decay_ms     @default 260  @min 1     @max 5000 @unit ms)
(param amp_sustain      @default 0.72 @min 0     @max 1)
(param amp_release_ms   @default 260  @min 1     @max 5000 @unit ms)

(param ratio_a          @default 1.0  @min 0.125 @max 16 @mod true @mod-mode additive)
(param ratio_b          @default 2.0  @min 0.125 @max 16 @mod true @mod-mode additive)
(param ratio_c          @default 1.0  @min 0.125 @max 16 @mod true @mod-mode additive)
(param ratio_d          @default 3.0  @min 0.125 @max 16 @mod true @mod-mode additive)

(param index_a          @default 0.8  @min 0     @max 16 @mod true @mod-mode additive)
(param index_b          @default 0.0  @min 0     @max 16 @mod true @mod-mode additive)
(param dyn_index_amt    @default 0.8  @min -16   @max 16)
(param feedback_a       @default 0.03 @min 0     @max 1.4 @mod true @mod-mode additive)
(param feedback_b       @default 0.0  @min 0     @max 1.4 @mod true @mod-mode additive)
(param crossmod         @default 0.0  @min 0     @max 8 @mod true @mod-mode additive)
(param self_fm          @default 0.0  @min 0     @max 8 @mod true @mod-mode additive)
(param ratio_warp       @default 0.0  @min -8    @max 8 @mod true @mod-mode additive)
(param glitch_rate      @default 0.0  @min 0     @max 80 @unit Hz)
(param glitch_amt       @default 0.0  @min 0     @max 1 @mod true @mod-mode additive)

(param parallel_mix     @default 0.0  @min 0     @max 1 @mod true @mod-mode additive)
(param tone             @default 5600 @min 80    @max 12000 @unit Hz @mod true @mod-mode additive)
(param resonance        @default 0.6  @min 0.35  @max 3.5)
(param keytrack         @default 0.22 @min 0     @max 2)
(param filter_drive     @default 1.0  @min 0.5   @max 4)
(param gain             @default 0.11 @min 0     @max 1)

(def amp_env (adsr gate trigger amp_attack_ms amp_decay_ms amp_sustain amp_release_ms))
(def ln2 (log 2))
(def glitch_rate_ctl (+ 0.05 glitch_rate))
(def glitch_trig (max trigger (lt (phasor glitch_rate_ctl) 0.001)))
(def glitch_step (latch (noise) glitch_trig))
(def base pitch)
(def ratio_warp_ctl (mod ratio_warp))
(def warp_a (exp (* ln2 (/ (+ ratio_warp_ctl (* glitch_step glitch_amt 6)) 12))))
(def warp_b (exp (* ln2 (/ (- ratio_warp_ctl (* glitch_step glitch_amt 4)) 12))))

(def phase_a (phasor (* base (clip (mod ratio_a) 0.125 16) warp_a)))
(def phase_b (phasor (* base (clip (mod ratio_b) 0.125 16) warp_b)))
(def phase_c (phasor (* base (clip (mod ratio_c) 0.125 16) warp_b)))
(def phase_d (phasor (* base (clip (mod ratio_d) 0.125 16) warp_a)))

(make-history fb_a_hist)
(make-history fb_b_hist)
(make-history car_a_hist)
(make-history car_b_hist)
(def fb_a (read-history fb_a_hist))
(def fb_b (read-history fb_b_hist))
(def car_a_prev (read-history car_a_hist))
(def car_b_prev (read-history car_b_hist))

(def mod_a (sin (+ (* twopi phase_b) (* fb_a (clip (mod feedback_a) 0 1.4)) (* car_a_prev (clip (mod self_fm) 0 8)))))
(def mod_b (sin (+ (* twopi phase_d) (* fb_b (clip (mod feedback_b) 0 1.4)) (* car_b_prev (clip (mod self_fm) 0 8) 0.7))))
(write-history fb_a_hist mod_a)
(write-history fb_b_hist mod_b)

(def dyn_index (mod index_a))
(def index_b_ctl (mod index_b))
(def crossmod_ctl (clip (mod crossmod) 0 8))
(def glitch_amt_ctl (clip (mod glitch_amt) 0 1))
(def car_a (sin (+ (* twopi phase_a) (* mod_a dyn_index) (* mod_b crossmod_ctl) (* glitch_step (* glitch_amt_ctl 2.2)))))
(def car_b (sin (+ (* twopi phase_c) (* mod_b index_b_ctl) (* mod_a (* crossmod_ctl 0.5)) (* glitch_step (* glitch_amt_ctl 1.3)))))
(write-history car_a_hist car_a)
(write-history car_b_hist car_b)

(def fm_mix (mix car_a (+ (* 0.82 car_a) (* 0.82 car_b)) (clip (mod parallel_mix) 0 1)))
(def voiced (* fm_mix (+ 0.25 (* 0.75 velocity))))
(def hot (tanh (* voiced filter_drive)))
(def tone_ctl (apply_cutoff_mod_safe (+ (mod tone) (* base keytrack) (* fm_mix glitch_amt_ctl 2400)) 0 1))
(def filtered (biquad hot tone_ctl resonance 1 0))
(out (* filtered amp_env gain) 1 @name audio)
